spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akshaywa/SpringBoot-Microservices
          clone-on-start: true

server:
  port: 9296

