spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/order
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/payment

resilience4j:
  circuitbreaker:
    instances:
      orderServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 2
        slidingWindowSize: 2
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2

      productServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 2
        slidingWindowSize: 2
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2

      paymentServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 2
        slidingWindowSize: 2
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 9090
