spring:
  application:
    name: AUTH-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://admin:mwcSVXJCDZK02NYO@cluster0.19ahm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: userdb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  config:
    import: configserver:http://localhost:9296

management:
  tracing:
    enabled: false

server:
  port: 8088