spring:
  application:
    name: AUTH-SERVICE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  config:
    import: configserver:http://localhost:9296

management:
  tracing:
    enabled: false

server:
  port: 8088