spring:
  application:
    name: Order-Service
  data:
    mongodb:
      uri: mongodb+srv://walunja11:LO56EsJAxpdErHEH@cluster0.tmq9eqi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: productdb
  config:
    import: configserver:http://localhost:9296


server:
  port: 8082

